### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by CryogenicPlanet** [tanviroy/forkify#1]
Hey you should deploy the project so people can access it, you can do it using netlify in a few clicks its super simple.

https://www.netlify.com/

**Comment by tanviroy** [comment]
> Hey you should deploy the project so people can access it, you can do it using netlify in a few clicks its super simple.
> 
> https://www.netlify.com/

Hey totally forgot to do this thank you for raising this!
[https://tanviroy-forkify.netlify.app/](https://tanviroy-forkify.netlify.app/)
